- README.md
- package.json
- web/global.css
- web/privacy.html
- web/unified.html
- yarn.lock
added custom login for developer portal
> feat: custom login style and privacy policy

- src/app.ts
ref. https://github.com/teamdigitale/digital-citizenship/issues/123
> fix: first / last name mismatch

- src/app.ts
- src/fake_profile.ts
- src/service.ts
needed to create services for testing purpose
> feat: added organization_fiscal_code

- .gitignore
- src/app.ts
> service fiscal code

- package-lock.json
- package.json
> [#168895578] Fix build

- package.json
- src/app.ts
- src/controllers/services.ts
- yarn.lock
To allow the metadata update for the admin user, the payload of the _PUT services_ is updated adding:
- `service_metadata : ServiceMetadata`
> [#175160851] Add possibility to update metadata for admin 

- web/privacy.html
Replacing old privacy policy provided by AgID with new policy provided by PagoPA as data controller for processing of developers' personal data. 
Closed the stylesheet tag that prevented from loading applicable css rules. Introduced additional style rules to allow indented unordered list. 
Attaching screenshots providing preview of code for browsers, tablets and mobile.
This is my first PR so feedback is welcome.
> update privacy policy

- .devops/deploy-pipelines.yml
Changes after https://github.com/pagopa/gitops/pull/208
> [#IC-148] Deploy on `SelfCare IO` instances

- src/auth-strategies/selfcare_identity_strategy.ts
- src/auth-strategies/selfcare_session_strategy.ts
- src/config.ts
Minor fixes to align token resolution with what is actually delivered by SelfCare
> [#IC-166] Fix token resolution

- package.json
- src/auth-strategies/selfcare_identity_strategy.ts
- src/config.ts
- yarn.lock
`SelfCare IO` will dynamically resolve public signature key to verify incoming IdentityToken. Wait for https://github.com/pagopa/io-infra/pull/67 before merging
> [#IC-160] Implement jwks resolution

- src/controllers/subscriptions.ts
- src/new_subscription.ts
> [#IOPAE-28]  Enforce organization values on subscriptions

- unified.html
Forgot password link updated to correct link
broken link
> [IOPAE-102] Update reset password link

- src/apim_operations.ts
- src/app.ts
- src/controllers/subscriptions.ts
- src/utils/__tests__/apim_filter.test.ts
- src/utils/api_key.ts
- src/utils/apim_filters.ts
Add *name* optional parameter to GetSubscriptions
- Added optional parameter *name* to *GetSubscriptions*
- Added *apim_filter* utility to build APIM `$filter` string
We need this additional filter in order to improve subscription search (especially from Dev Portal Frontend).
> [#IOPSC-132] Subscriptions filter by name

- src/app.ts
> Enable application insights auto-tracing

- .devops/code-review-pipelines.yml
- src/api_client.ts
- src/app.ts
- src/controllers/__tests__/subscriptions.test.ts
- src/controllers/subscriptions.ts
- src/new_subscription.ts
Add Get/Update Manage Subscription CIDRs to the project.
These APIs are required for manage flow.
- Added new Get/Update Subscription Manage APIs
- Subscription Unit Tests
We need to get/update Subscription Cidrs on admin level.
Unit Tests, directly with BackOffice frontend
> [#IOPAE-184] Update Subscription Cidrs

- src/config.ts
- src/controllers/__tests__/subscriptions.test.ts
- src/controllers/subscriptions.ts
We have a feature _(manage key)_ that we don't enable for users EXCEPT the ones in an enabling list _(MANAGE_FLOW_ENABLE_USER_LIST config key)_.
The enabling list is a list of strings that represents a user id.
The new feature is that **_"If one of such strings is "*", we suddenly open the feature to everyone."_**.
**Note:**
_A change on `io-infra > core > devportal.tf` is required in order to allow all users_.
_Change `MANAGE_FLOW_ENABLE_USER_LIST` value to `*`_.
- subscriptions controller
We need to rollout MANAGE API KEY to all APIM users.
Unit Tests and integration test with local environment (be/fe).
> [#IOPAE-327] Add check on wildcard for enable all users to manage key

- package.json
- yarn.lock
Added Azurestorage explicit Dependencies.
- Add `azure-storage` dependency
- Add `postbuild` script, to check dependency misalignment
- Add explicit `logForm` dependency
- Add resolution for `xml2js`
> chore: fix: bug: [IOPAE-489] Fix azure-storage dependency

- package.json
- yarn.lock
Removed Resolution for `xml2js`^0.5.0 in order to use the hoisted one from `azure-storage`
> chore: fix: bug: [IOPAE-489] Xml2Js dep revert

- src/controllers/services.ts
Add apimUserId on `request-review-legacy` queue message.
> [IOPAE-489] Add apim user id on request-review-legacy queue message

- src/controllers/services.ts
Added the possibility to have `require_secure_channels` in `ServicePayload` for service update.
This new feature has been developed in the context of "privacy critical" services and the need to control the `require_secure_channels` _flag_ via the Developer Portal.
- Added require_secure_channels in ServicePayload
> [#IOPAE-587] Add require_secure_channels to ServicePayload

- .devops/deploy-pipelines.yml
- src/apim_operations.ts
- src/app.ts
- src/cms_api_client.ts
- src/config.ts
- src/controllers/services.ts
- src/middlewares/api_client.ts
We introduce a check to block update service request if there are changes "in progress" by Services CMS "parallel" system.
- [add cms api client](https://github.com/pagopa/io-developer-portal-backend/commit/74df61c3cacaebb46fca7403bf1850e68f205473)
- [add middleware to create and inject cms api client to handler](https://github.com/pagopa/io-developer-portal-backend/commit/83516830f560e33198a60938b313916730e3c716)
- [add cms sync check to update service handler](https://github.com/pagopa/io-developer-portal-backend/commit/11fb27c6607a71419543820410930fc74e2ad85b)
local run of the application
> [IOPAE-907] add sync check

- src/cms_api_client.ts
Add verbose log in case of failed cms api call while updating a service
> [IOPAE-907] Add verbose log in case of failed cms api call

- src/cms_api_client.ts
Fix log on cms call error while updating service
> [#IOPAE-907] Fix log on cms call error

- src/cms_api_client.ts
Fix log cms api call error while updating service
> [IOPAE-907] Fix log cms api call error

- src/controllers/services.ts
Append ApiServiceWrite permission on get service publication call while updating a service
> [#IOPAE-907] Add needed permission on cms api call

- src/cms_api_client.ts
Call internal CMS API when updating service
> [IOPAE-907] Call internal CMS API when updating service

- src/controllers/services.ts
Remove possibility to edit Deleted services from devportal
> [#IOPAE-1011] Block edit on deleted services

- src/controllers/services.ts
change update so when a service is deleted on devportal (add DELETE before name) the service gets unpublished too (is_visible = false)
> [#IOPAE-1011]set is_visible to false when deleting service

- src/cms_api_client.ts
- src/controllers/services.ts
Avoid having multiple service with the same name for an organization by checking for.
> [#IOPAE-1089] Check if the service is a pure duplicate on service activation

- src/controllers/services.ts
It should not be possible to modify a service if it has a pending review
> [IOPAE-1099] block service update on submitted services

- src/config.ts
- src/middlewares/api_client.ts
Dynamic Apim Auth config params get
> [IOPAE-11133] Dynamic Apim Auth config params get

- src/middlewares/api_client.ts
> [IOPAE-1133] Add authorityHost on ClientCredentials

- src/apim_operations.ts
> [IOPAE-1133] Fix Check Ownership

- src/apim_operations.ts
RegenerateKey now returns the regenerated Keys on response
> [IOPAE-1133] RegenerateKey now returns the regenerated Keys on response

- package.json
- src/app.ts
- yarn.lock
Update applicationInsight sdk version, setAutoCollectConsole on ApplicationInsight
> [IOPAE-1133] setAutoCollectConsole on ApplicationInsight

- src/apim_operations.ts
- src/app.ts
- src/cms_api_client.ts
- src/controllers/services.ts
- src/logger.ts
Send Only Info or Above logs to ApplicationInsight
> [IOPAE-1133]Send only info and above log to applicationInsight

- .devops/deploy-pipelines.yml
change deploy from prod to staging for testing purpose
> change deploy from prod to staging
